# Generated by Django 4.2.3 on 2023-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audio_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.SmallIntegerField()),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('updated', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
