# Generated by Django 4.2.3 on 2023-07-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_list',
            name='content',
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('audio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asr.audio_list')),
            ],
        ),
        migrations.CreateModel(
            name='audio_transcription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=200)),
                ('start_sec', models.PositiveIntegerField()),
                ('end_sec', models.PositiveIntegerField()),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asr.version')),
            ],
        ),
    ]
